graph LR
    %% Mermaid input file for drawing task dependencies 
    %% See https://mermaid-js.github.io/mermaid
    %%
    TASK_SPAN_ID_0xf90dd8178457cf79["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/ingest/runs/0x01d4fa14c0dc5ef7' style='text-decoration: none; color: black;'><b>notebooks/ingest.py (jupytext task) 🔗</b> <br />task.max_nr_retries=15<br />task.num_cpus=1<br />task.timeout_s=10</a>"]
    TASK_SPAN_ID_0x5baf4e2f92221001["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/eda/runs/0xdb2c141fe7f8dfd7' style='text-decoration: none; color: black;'><b>notebooks/eda.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x979fdfefd519eac5["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/split-train-test/runs/0x25b941737e666649' style='text-decoration: none; color: black;'><b>notebooks/split-train-test.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1<br />task.train_test_ratio=0.7</a>"]
    TASK_SPAN_ID_0x35c3feebc8d18f94["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x10cf5d62558dc5d3' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x1ff50fa064fbe211["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x30d6e773faaae941' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xfca43ef5728b8d26["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x94dadb92602fc3f7' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x649fdd8998878e12["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x252134df24e790af' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x196a13ad434fad22["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x19339f7496dc29f5' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x23201fc22fa8a9c6["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0xda5423fe6a5e303f' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xb095765d1ed13eb0["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x72f4ee3a236da443' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xa9e0b7cdd87d0bc9["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0xa92a828e6673eade' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xcfcb18c3b197e320["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/summary/runs/0x18449af91cac0e61' style='text-decoration: none; color: black;'><b>notebooks/summary.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x649fdd8998878e12 --> TASK_SPAN_ID_0xa9e0b7cdd87d0bc9
    TASK_SPAN_ID_0x1ff50fa064fbe211 --> TASK_SPAN_ID_0x23201fc22fa8a9c6
    TASK_SPAN_ID_0x979fdfefd519eac5 --> TASK_SPAN_ID_0x1ff50fa064fbe211
    TASK_SPAN_ID_0x35c3feebc8d18f94 --> TASK_SPAN_ID_0x196a13ad434fad22
    TASK_SPAN_ID_0xf90dd8178457cf79 --> TASK_SPAN_ID_0x5baf4e2f92221001
    TASK_SPAN_ID_0x979fdfefd519eac5 --> TASK_SPAN_ID_0x35c3feebc8d18f94
    TASK_SPAN_ID_0xfca43ef5728b8d26 --> TASK_SPAN_ID_0xb095765d1ed13eb0
    TASK_SPAN_ID_0x979fdfefd519eac5 --> TASK_SPAN_ID_0xfca43ef5728b8d26
    TASK_SPAN_ID_0x979fdfefd519eac5 --> TASK_SPAN_ID_0x649fdd8998878e12
    TASK_SPAN_ID_0xf90dd8178457cf79 --> TASK_SPAN_ID_0x979fdfefd519eac5