graph LR
    %% Mermaid input file for drawing task dependencies 
    %% See https://mermaid-js.github.io/mermaid
    %%
    TASK_SPAN_ID_0xb45fd098cfa51329["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/ingest/runs/0x6c4e28278dde1dd2' style='text-decoration: none; color: black;'><b>notebooks/ingest.py (jupytext task) 🔗</b> <br />task.max_nr_retries=15<br />task.num_cpus=1<br />task.timeout_s=10</a>"]
    TASK_SPAN_ID_0x2f7e28c5b2b01def["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/eda/runs/0x2e185a48b7dd62cf' style='text-decoration: none; color: black;'><b>notebooks/eda.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xe6ad91910316a14c["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/split-train-test/runs/0x78c5985d03853070' style='text-decoration: none; color: black;'><b>notebooks/split-train-test.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1<br />task.train_test_ratio=0.7</a>"]
    TASK_SPAN_ID_0x5e068e661f1903ed["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x507ff1fb775b7330' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xe80c97b765b4b654["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x5aeb5317a802a344' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x57cf6b4db0d9caf7["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0xbb3fa703595edb1d' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xac2a9dfbc13524a1["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0xaa54f027fc70373e' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x3d07736608c7d887["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0xbe9bf8ed74a41a37' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xd80b421e0ed82695["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0xd79e274049cd9f2e' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xd7f97c55c5cafe26["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x4aecfdf816fb4974' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xa5ff27f8983ca7b0["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x5039e1147528ad71' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x50a8b78fd67b31a1["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/summary/runs/0x80b8130a8533bc05' style='text-decoration: none; color: black;'><b>notebooks/summary.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xd80b421e0ed82695 --> TASK_SPAN_ID_0x50a8b78fd67b31a1
    TASK_SPAN_ID_0xb45fd098cfa51329 --> TASK_SPAN_ID_0x2f7e28c5b2b01def
    TASK_SPAN_ID_0xa5ff27f8983ca7b0 --> TASK_SPAN_ID_0x50a8b78fd67b31a1
    TASK_SPAN_ID_0xe6ad91910316a14c --> TASK_SPAN_ID_0xac2a9dfbc13524a1
    TASK_SPAN_ID_0xac2a9dfbc13524a1 --> TASK_SPAN_ID_0xd80b421e0ed82695
    TASK_SPAN_ID_0xb45fd098cfa51329 --> TASK_SPAN_ID_0xe6ad91910316a14c
    TASK_SPAN_ID_0xe6ad91910316a14c --> TASK_SPAN_ID_0x57cf6b4db0d9caf7
    TASK_SPAN_ID_0x3d07736608c7d887 --> TASK_SPAN_ID_0x50a8b78fd67b31a1
    TASK_SPAN_ID_0x5e068e661f1903ed --> TASK_SPAN_ID_0x3d07736608c7d887
    TASK_SPAN_ID_0xe6ad91910316a14c --> TASK_SPAN_ID_0xe80c97b765b4b654
    TASK_SPAN_ID_0xe80c97b765b4b654 --> TASK_SPAN_ID_0xd7f97c55c5cafe26
    TASK_SPAN_ID_0xd7f97c55c5cafe26 --> TASK_SPAN_ID_0x50a8b78fd67b31a1
    TASK_SPAN_ID_0x57cf6b4db0d9caf7 --> TASK_SPAN_ID_0xa5ff27f8983ca7b0
    TASK_SPAN_ID_0xe6ad91910316a14c --> TASK_SPAN_ID_0x5e068e661f1903ed