graph LR
    %% Mermaid input file for drawing task dependencies 
    %% See https://mermaid-js.github.io/mermaid
    %%
    TASK_SPAN_ID_0xd588b25ed9184d71["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/ingest/runs/0x74f33f45dfbf10c5' style='text-decoration: none; color: black;'><b>notebooks/ingest.py (jupytext task) 🔗</b> <br />task.max_nr_retries=15<br />task.num_cpus=1<br />task.timeout_s=10</a>"]
    TASK_SPAN_ID_0x178ceaed076f12ba["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/eda/runs/0x879579b5b88a7b5e' style='text-decoration: none; color: black;'><b>notebooks/eda.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x80d38c1d4ccc6c9c["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/split-train-test/runs/0xe8eec15915c55ce6' style='text-decoration: none; color: black;'><b>notebooks/split-train-test.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1<br />task.train_test_ratio=0.7</a>"]
    TASK_SPAN_ID_0x56ebb39c1a60a97a["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x20c45626c9920e5e' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xdfc0e6fdb263cc30["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0xc58ae869913d988f' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x8abfaa97318a523c["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0xf5d39fd4d28af7dd' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xb0ce07e24be68bac["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0xfb5d46db073b3174' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x33213f2667a2b45c["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x8f4b9ac3fae158e9' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x02eda1e9c8e094ef["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0xd8b4095150c88b54' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x9b1d3d585c98d82b["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x9069b719a84e3c97' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xc4286012447af252["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0xef4c70f6fbb41726' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x32324b46419d9b78["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/summary/runs/0xc4e2bba9ed3da1bf' style='text-decoration: none; color: black;'><b>notebooks/summary.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x80d38c1d4ccc6c9c --> TASK_SPAN_ID_0xdfc0e6fdb263cc30
    TASK_SPAN_ID_0x80d38c1d4ccc6c9c --> TASK_SPAN_ID_0xb0ce07e24be68bac
    TASK_SPAN_ID_0x56ebb39c1a60a97a --> TASK_SPAN_ID_0x33213f2667a2b45c
    TASK_SPAN_ID_0x80d38c1d4ccc6c9c --> TASK_SPAN_ID_0x56ebb39c1a60a97a
    TASK_SPAN_ID_0xd588b25ed9184d71 --> TASK_SPAN_ID_0x80d38c1d4ccc6c9c
    TASK_SPAN_ID_0x80d38c1d4ccc6c9c --> TASK_SPAN_ID_0x8abfaa97318a523c
    TASK_SPAN_ID_0x02eda1e9c8e094ef --> TASK_SPAN_ID_0x32324b46419d9b78
    TASK_SPAN_ID_0xdfc0e6fdb263cc30 --> TASK_SPAN_ID_0x02eda1e9c8e094ef
    TASK_SPAN_ID_0x9b1d3d585c98d82b --> TASK_SPAN_ID_0x32324b46419d9b78
    TASK_SPAN_ID_0x8abfaa97318a523c --> TASK_SPAN_ID_0x9b1d3d585c98d82b
    TASK_SPAN_ID_0xd588b25ed9184d71 --> TASK_SPAN_ID_0x178ceaed076f12ba
    TASK_SPAN_ID_0x33213f2667a2b45c --> TASK_SPAN_ID_0x32324b46419d9b78
    TASK_SPAN_ID_0xc4286012447af252 --> TASK_SPAN_ID_0x32324b46419d9b78
    TASK_SPAN_ID_0xb0ce07e24be68bac --> TASK_SPAN_ID_0xc4286012447af252