graph LR
    %% Mermaid input file for drawing task dependencies 
    %% See https://mermaid-js.github.io/mermaid
    %%
    TASK_SPAN_ID_0xa89121666882529a["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/ingest/runs/0x8e327c8f8c87d559' style='text-decoration: none; color: black;'><b>notebooks/ingest.py (jupytext task) 🔗</b> <br />task.max_nr_retries=15<br />task.num_cpus=1<br />task.timeout_s=10</a>"]
    TASK_SPAN_ID_0xdbdfdc5e4b18cc3d["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/eda/runs/0x6288a0674001a7cc' style='text-decoration: none; color: black;'><b>notebooks/eda.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x60f0d36812e44e90["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/split-train-test/runs/0x2f6ff2f117e653c0' style='text-decoration: none; color: black;'><b>notebooks/split-train-test.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1<br />task.train_test_ratio=0.7</a>"]
    TASK_SPAN_ID_0xdff1ab21d764b6de["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0xe165e5a377c4dc38' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x0cb7edaeabbb61c5["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x84692ed8a7983bbb' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x2817290816596c71["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0xef9d76cd2f12444e' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x99bd3543798698e6["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/train-model/runs/0x31f413257f12e377' style='text-decoration: none; color: black;'><b>notebooks/train-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x1cbd653802cc8b1f["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0xf8ec4f0b8c2d37bc' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=600<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x01296fb44bdffd3c["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x4d0683f363aa3789' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=800<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xcbb9e6e42404ae7e["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x68218f5f0f27e748' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1000<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x2c2c16ccb1a654ab["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/benchmark-model/runs/0x89a962edaa91aca4' style='text-decoration: none; color: black;'><b>notebooks/benchmark-model.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.nr_train_images=1200<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0xbadf53c29e4dfc4f["<a href='https://matiasdahl.github.io/dev-mnist-digits-demo-pipeline/#/experiments/summary/runs/0xfc43f4af8713a36a' style='text-decoration: none; color: black;'><b>notebooks/summary.py (jupytext task) 🔗</b> <br />task.max_nr_retries=1<br />task.num_cpus=1</a>"]
    TASK_SPAN_ID_0x2817290816596c71 --> TASK_SPAN_ID_0xcbb9e6e42404ae7e
    TASK_SPAN_ID_0x0cb7edaeabbb61c5 --> TASK_SPAN_ID_0x01296fb44bdffd3c
    TASK_SPAN_ID_0x60f0d36812e44e90 --> TASK_SPAN_ID_0x0cb7edaeabbb61c5
    TASK_SPAN_ID_0x60f0d36812e44e90 --> TASK_SPAN_ID_0x99bd3543798698e6
    TASK_SPAN_ID_0xa89121666882529a --> TASK_SPAN_ID_0x60f0d36812e44e90
    TASK_SPAN_ID_0x60f0d36812e44e90 --> TASK_SPAN_ID_0x2817290816596c71
    TASK_SPAN_ID_0xa89121666882529a --> TASK_SPAN_ID_0xdbdfdc5e4b18cc3d
    TASK_SPAN_ID_0xdff1ab21d764b6de --> TASK_SPAN_ID_0x1cbd653802cc8b1f
    TASK_SPAN_ID_0x99bd3543798698e6 --> TASK_SPAN_ID_0x2c2c16ccb1a654ab
    TASK_SPAN_ID_0x60f0d36812e44e90 --> TASK_SPAN_ID_0xdff1ab21d764b6de