name: "Reusable workflow to update static website"

# References on reusable workflows:
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
# - https://github.community/t/cant-call-reusable-workflow-unexpected-value-uses/204182

on:
  workflow_call:

jobs:
  update-static-website:
    name: Build and deploy static website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/pynb-dag-runner
          path: pynb-dag-runner-repo
          persist-credentials: true

      - name: "Build Docker file"
        working-directory: ${{ github.workspace }}/pynb-dag-runner-repo/otel_output_parser
        shell: bash
        run: |
          make docker-build

      - name: "Fetch all artefacts into directory tree"
        working-directory: ${{ github.workspace }}/pynb-dag-runner-repo/otel_output_parser
        shell: bash
        run: |
          # GITHUB_REPOSITORY has format owner/repo-name.
          make docker-run-command \
              DOCKER_RUN_ARGS="\
                  --volume ${{ github.workspace }}:/github_workspace \
                  -e GITHUB_TOKEN \
                  -e GITHUB_REPOSITORY \
              " \
              COMMAND="\
                  pip install -e .; \
                  static_builder \
                      --github_repository $GITHUB_REPOSITORY \
                      --output_dir /github_workspace/www-root/pipeline-artifacts/ \
                      --output_static_data_json /github_workspace/ui_static_data.json; \
              "

          # Make .js version of static data
          echo "export const STATIC_DATA = "                >   ${{ github.workspace }}/ui_static_data.js
          cat  ${{ github.workspace }}/ui_static_data.json  >>  ${{ github.workspace }}/ui_static_data.js
          echo ";"                                          >>  ${{ github.workspace }}/ui_static_data.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ###
      ### Make static ML Flow
      ###
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/mlflow
          persist-credentials: true
          path: mlflow-repo
          # replace below with feature branch of `mlflow` repo for testing new
          # UI features using logs from this repo
          ref: load-data-dynamically # dummy edit

      # export static ui data (for easier offline debugging)
      - name: "Store ui_static_data.json with data for UI"
        uses: actions/upload-artifact@v2
        with:
          name: ui-static-data
          path: |
              ${{ github.workspace }}/ui_static_data.js
              ${{ github.workspace }}/ui_static_data.json
          if-no-files-found: error
          retention-days: 5

      - name: "Build static ML Flow"
        working-directory: ${{ github.workspace }}/mlflow-repo/mlflow/server/js
        shell: bash
        run: |
          # copy static pipeline-task-run into ui-source directory
          cp ${{ github.workspace }}/ui_static_data.js \
             ./src/experiment-tracking/static-data/StaticData.js

          make docker-build-image-for-build-static-ui
          make docker-build-static-ui
          cp -r build/. ${{ github.workspace }}/www-root

          cp ${{ github.workspace }}/ui_static_data.json \
             ${{ github.workspace }}/www-root/


      ###
      ### Deploy
      ###
      - name: "Push www-root content to repo gh-pages branch"
        working-directory: ${{ github.workspace }}/www-root
        shell: bash
        run: |
          # Github pages does not allow directory listing, add files in root
          # for troubleshooting
          find . > list_all_files.txt
          du -hs * > disk_usage.txt

          git init
          git checkout -b gh-pages

          git add -A

          git config --local user.email "gh-automation-bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git commit -m "update"

          git push --force \
            https://my_token_user:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git \
            gh-pages:gh-pages
