name: "Run automated tests and the mnist-digit-demo-pipeline"

on:
  workflow_dispatch:

jobs:
  build-and-deploy-static-mlflow-site:
    permissions:
      contents: write # grant write access to update repo's static website

    uses: ${{ github.repository }}/.github/workflows/build-and-deploy-static-mlflow-site.yml@development
